services:
  db:
    image: postgres:latest
    container_name: db
    restart: "no"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
  web:
    build: .
    container_name: web
    command: python manage.py runserver 0.0.0.0:8000
    restart: "no"
    volumes:
      - django_data:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    env_file:
      - .env
    depends_on:
      - db

volumes:
  postgres_data:
  django_data: