# Generated by Django 5.1.4 on 2025-03-23 23:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asignaturas', '0006_remove_asignatura_co_requisitos_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Silabo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(default='UNIB.E-CGC-FOR-05', max_length=50)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateField(auto_now=True)),
                ('facultad', models.TextField()),
                ('carrera', models.TextField()),
                ('anio_academico', models.PositiveIntegerField()),
                ('periodo_academico', models.CharField(max_length=20)),
                ('fecha_inicio', models.DateField()),
                ('fecha_finalizacion', models.DateField()),
                ('horario_clase', models.CharField(max_length=50)),
                ('horas_tutorias', models.PositiveIntegerField(blank=True, null=True)),
                ('horario_tutorias', models.CharField(blank=True, max_length=50, null=True)),
                ('caracterizacion_asignatura', models.TextField()),
                ('objetivos', models.TextField()),
                ('competencias_transversales', models.TextField()),
                ('competencias_profesionales', models.TextField()),
                ('metodologia', models.TextField()),
                ('evaluacion', models.TextField()),
                ('bibliografia', models.TextField()),
                ('anexos', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('aprobado', 'Aprobado'), ('pendiente', 'Pendiente'), ('rechazado', 'Rechazado')], default='pendiente', max_length=30)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syllabus_asignatura', to='asignaturas.asignatura')),
                ('docente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='syllabus_docente', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contenido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semana', models.PositiveIntegerField()),
                ('contenido', models.TextField()),
                ('actividades_docente', models.TextField(blank=True, null=True)),
                ('horas_docente', models.PositiveIntegerField(blank=True, null=True)),
                ('actividades_practicas', models.TextField(blank=True, null=True)),
                ('horas_practica', models.PositiveIntegerField(blank=True, null=True)),
                ('actividades_autonomas', models.TextField(blank=True, null=True)),
                ('horas_autonomas', models.PositiveIntegerField(blank=True, null=True)),
                ('resultados', models.TextField()),
                ('evidencias', models.TextField()),
                ('observacion', models.TextField(blank=True, null=True)),
                ('completado', models.BooleanField(default=False)),
                ('syllabus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contenido_syllabus', to='syllabus.silabo')),
            ],
        ),
        migrations.CreateModel(
            name='Aporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aporte', models.PositiveIntegerField()),
                ('actividades', models.PositiveIntegerField()),
                ('examen', models.PositiveIntegerField()),
                ('proyecto_final', models.PositiveIntegerField()),
                ('total', models.PositiveIntegerField()),
                ('syllabus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aporte_syllabus', to='syllabus.silabo')),
            ],
        ),
    ]
