# Generated by Django 5.1.4 on 2024-12-21 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='silabo',
            name='carrera',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='silabo',
            name='facultad',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='silabo',
            name='horario_tutorias',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='silabo',
            name='horas_tutorias',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
