# Generated by Django 5.1.4 on 2024-12-21 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0002_alter_silabo_carrera_alter_silabo_facultad_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='silabo',
            old_name='competencias',
            new_name='competencias_transversales',
        ),
    ]
