# Generated by Django 5.1.4 on 2024-12-22 02:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0004_contenido'),
    ]

    operations = [
        migrations.AddField(
            model_name='silabo',
            name='fecha_creacion',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Aporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aporte', models.PositiveIntegerField()),
                ('actividades', models.PositiveIntegerField()),
                ('examen', models.PositiveIntegerField()),
                ('proyecto_final', models.PositiveIntegerField()),
                ('total', models.PositiveIntegerField()),
                ('syllabus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aporte_syllabus', to='syllabus.silabo')),
            ],
        ),
    ]
