# Generated by Django 5.1.4 on 2025-01-21 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0006_contenido_observacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='silabo',
            name='periodo_academico',
            field=models.CharField(max_length=20),
        ),
    ]
