# Generated by Django 5.1.4 on 2025-03-23 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0008_contenido_completado'),
    ]

    operations = [
        migrations.AddField(
            model_name='silabo',
            name='estado',
            field=models.CharField(choices=[('aprobado', 'Aprobado'), ('pendiente', 'Pendiente'), ('Rechazado', 'Rechazado')], default='pendiente', max_length=30),
        ),
    ]
