# Generated by Django 5.1.4 on 2025-03-23 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0009_silabo_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='silabo',
            name='estado',
            field=models.CharField(choices=[('aprobado', 'Aprobado'), ('pendiente', 'Pendiente'), ('rechazado', 'Rechazado')], default='pendiente', max_length=30),
        ),
    ]
