# Generated by Django 5.1.4 on 2024-12-21 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('codigo', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('eje_formacion', models.CharField(max_length=50)),
                ('nivel_academico', models.PositiveIntegerField()),
                ('creditos', models.PositiveIntegerField()),
                ('totla_horas', models.PositiveIntegerField()),
                ('pre_requisitos', models.TextField()),
                ('co_requisitos', models.TextField()),
            ],
        ),
    ]
