# Generated by Django 5.1.4 on 2024-12-21 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asignaturas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asignatura',
            old_name='totla_horas',
            new_name='total_horas',
        ),
    ]
