# Generated by Django 5.1.4 on 2024-12-21 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignaturas', '0002_rename_totla_horas_asignatura_total_horas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignatura',
            name='co_requisitos',
            field=models.TextField(default='Ninguno'),
        ),
        migrations.AlterField(
            model_name='asignatura',
            name='pre_requisitos',
            field=models.TextField(default='Ninguno'),
        ),
    ]
