# Generated by Django 5.1.4 on 2024-12-26 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignaturas', '0004_docente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignatura',
            name='pre_requisitos',
        ),
        migrations.AddField(
            model_name='asignatura',
            name='pre_requisitos',
            field=models.ManyToManyField(blank=True, related_name='prerequisito', to='asignaturas.asignatura'),
        ),
    ]
