# Generated by Django 5.1.4 on 2024-12-26 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignaturas', '0005_remove_asignatura_pre_requisitos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignatura',
            name='co_requisitos',
        ),
        migrations.AddField(
            model_name='asignatura',
            name='co_requisitos',
            field=models.ManyToManyField(blank=True, related_name='corequisito', to='asignaturas.asignatura'),
        ),
    ]
