# Generated by Django 5.1.4 on 2024-12-22 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_formation'),
        ('asignaturas', '0003_alter_asignatura_co_requisitos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='asignatura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='docente_asignatura', to='asignaturas.asignatura'),
        ),
    ]
