# Generated by Django 5.1.4 on 2024-12-22 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_asignatura'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='asignatura',
        ),
    ]
