# Generated by Django 5.1.4 on 2024-12-22 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_customuser_asignatura'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='formation',
            new_name='formacion',
        ),
    ]
