# Generated by Django 5.1.4 on 2024-12-23 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_formation_customuser_formacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='rol_academico',
            field=models.CharField(choices=[('admin', 'Administrador'), ('full_time', 'Docente Tiempo Completo'), ('part_time', 'Docente Tiempo Parcial'), ('guest', 'Docente Invitado')], default=1, max_length=50, verbose_name='Rol Académico de Docente'),
            preserve_default=False,
        ),
    ]
